language: node_js
node_js:
  - "0.10"
  - "0.11"
before_install:
  - sudo apt-get install rubygems
  - sudo apt-get update
  - sudo npm install -g mocha
  - sudo npm install -g gulp
  - sudo npm install -g jade
  - sudo gem install sass
  - sudo npm install -g coffee-script
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b11b1afc4686781d7038
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
