language: node_js
node_js:
  - "0.10"
  - "0.11"
before_install:
  - sudo apt-get install rubygems
  - sudo apt-get update
  - npm install -g mocha -d
  - npm install -g gulp -d
  - npm install -g jade -d
  - sudo gem install sass
  - npm install -g coffee-script -d
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b11b1afc4686781d7038
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
