language: node_js
node_js:
  - "0.10"
  - "0.11"
before_install:
  - npm install -g mocha
  - npm install -g gulp
  - npm install -g coffee-script -d
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b11b1afc4686781d7038
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
