// Generated by CoffeeScript 1.8.0
'use strict';
var $, cfg, cln_prefix, del, ff, gulp, order;

cfg = require('../config.json');

gulp = require('gulp');

$ = require('gulp-load-plugins')();

del = require('del');

ff = require('../index');

order = ['childs_need_to_be_deteled'];

cln_prefix = 'clean-';

order.forEach(function(the) {
  gulp.task(cln_prefix + the, function() {
    var ff_result;
    $.util.log('The results of the folder to be find found: ', ff(the, {
      nottraversal: ['.git', 'node_modules', 'backup']
    }));
    ff_result = ff(the, {
      nottraversal: ['.git', 'node_modules', 'backup']
    });
    ff_result.forEach(function(_item, _index, _array) {
      del(_item + '/*');
    });
  });
});

gulp.task('clean', order.map(function(the) {
  return cln_prefix + the;
}));
