// Generated by CoffeeScript 1.8.0
'use strict';
var $, cfg, gulp, parse_args, __args;

cfg = require('../config.json');

gulp = require('gulp');

$ = require('gulp-load-plugins')();

parse_args = require('minimist');

__args = parse_args(process.argv.slice(2), {
  'boolean': config.clp
});

module.exports = __args;
