// Generated by CoffeeScript 1.8.0
'use strict';
var $, cfg, gulp;

cfg = require('../config.json');

gulp = require('gulp');

$ = require('gulp-load-plugins')();

gulp.task('cmprs_index_js', function() {});

gulp.task('cmprs_tasks_js', function() {});
